app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# basic routes
homepage:
    path: /
    defaults: { _controller: AppBundle:User:register }

user_login_check:
    path: /login_check

user_logout:
    path: /logout