security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        main:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_admin

            logout:
                path: user_logout
                target: homepage

    access_control:
        - { path: ^/login,            roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,            roles: ROLE_USER }
        - { path: ^/,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }
